# https://marketplace.visualstudio.com/items?itemName=humao.rest-client

@idphost = http://localhost:55445
@host = http://localhost:55447
@contentType = application/json

###
# @name auth
POST {{idphost}}/connect/token HTTP/1.1
content-type: application/x-www-form-urlencoded

grant_type=password
&client_id=store.password
&client_secret=49C1A7E1-0C79-4A89-A3D6-A37998FB86B0
&username=bob
&password=bob

###
@term = Fashion
@page = 1
@pageSize = 20
GET {{host}}/products?term={{term}}&page={{page}}&pageSize={{pageSize}} HTTP/1.1
content-type: {{contentType}}

###
POST {{host}}/products HTTP/1.1
content-type: {{contentType}}
authorization: bearer {{auth.response.body.access_token}}

{
  "name": "sample 01",
  "modelYear": 2020,
  "listPrice": 1000,
  "brandId": 1,
  "categoryId": 1
}

###
GET {{host}}/categories HTTP/1.1
content-type: {{contentType}}
authorization: bearer {{auth.response.body.access_token}}
