# tye application configuration file
# read all about it at https://github.com/dotnet/tye
#
# when you've given us a try, we'd love to know what you think:
#    https://aka.ms/AA7q20u
#
name: modernstore

extensions:
- name: dapr
  log-level: debug
  config: appconfig
  # components-path configures the components path of the dapr sidecard
  components-path: "./components/"

services:

- name: productionservice
  project: src/ProductionService/ProductionService.csproj

- name: saleservice
  project: src/SaleService/SaleService.csproj

- name: identityservice
  project: src/IdentityService/IdentityService.csproj

- name: appgateway
  project: src/Gateway/AppGateway.csproj

- name: sqlserver
  image: mcr.microsoft.com/mssql/server:2017-latest
  env:
    - name: SA_PASSWORD
      value: "P@ssw0rd"
    - name: ACCEPT_EULA
      value: "Y"
  bindings:
    - port: 1433
      connectionString: Data Source=${host},${port};Initial Catalog=modernstoredb;User Id=sa;Password=${env:SA_PASSWORD};MultipleActiveResultSets=True;

- name: redis
  image: redis
  bindings:
    - port: 6379

# To ensure that your are running a dapr placement container with the right binding port.
# (50005 as HostPort)
- name: placement
  image: daprio/dapr
  args: ./placement
  bindings:
    - port: 50005
